services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/home/rexes/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=rexes
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
